### ISSUE TITLE
Redirect click on "Ir al artista" label to artist profile on Song Context Menu 

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#130]
Redirect "Ir al artista" button on ContextMenuSong to artist profile page.

Create an onclick event and adapt this code to redirect into /artist/artist_name :

```
 const navigate = useNavigate();

 const urlUser = `/artist/${name}`;

  const handleClickGoToArtist = (event: any) => {
    event.preventDefault();
    event.stopPropagation();
    navigate(urlUser);
};
  ```

![imagen](https://github.com/AntonioMrtz/SpotifyElectron/assets/60626957/0a173c94-1b38-4155-bd89-2959124158a5)

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ir al artista context menu canciones o usuario en playlist](https://trello.com/c/Zs0QWSwv/237-ir-al-artista-context-menu-canciones-o-usuario-en-playlist)

**Comment by TalhaBinNasir** [comment]
Hi @AntonioMrtz, I'd like to help you with this issue. Could you assign me this?

**Comment by TalhaBinNasir** [comment]
https://github.com/AntonioMrtz/SpotifyElectron/pull/131

**Comment by TalhaBinNasir** [comment]
Here's the PR https://github.com/AntonioMrtz/SpotifyElectron/pull/131
