### ISSUE TITLE
Disable upload song button while processing request

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#133]
## Description

Modify the behaviour of upload song button so its disabled while waiting for the song to be uploaded. 

## Context

In component [AddSongPlayListAccordion.tsx](https://github.com/AntonioMrtz/SpotifyElectron/blob/master/Electron/src/components/Sidebar/ModalAddSongPlaylist/ModalAddSongPlaylist.tsx) when the user decides to upload a song the function `handleSubmitSong` is called. This function triggers an style change of the button so it displays a loading animation . The issues is that the user can still click it even if the upload song request is already being made.

The goal is to disable the button while still showing the loading animation so the user cannot upload the same song twice.

* This feature of uploading songs is currently only available for artists.
* It might be necessary to create an artist user using the interface of backend because right now theres no frontend component to register artists.

## How to do it

Manage an state of the request variable that disables/enables the button.

## Testing

* Create an artist, upload a song and check if the button goes disable and has a loading animation while the request is being processed.
* Create a test that checks if the button is disabled when the request is being made.

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deshabilitar botón de subir canción en caso de que la petición todavía se este realizando](https://trello.com/c/Qp2G3v9P/378-deshabilitar-bot%C3%B3n-de-subir-canci%C3%B3n-en-caso-de-que-la-petici%C3%B3n-todav%C3%ADa-se-este-realizando)

**Comment by ObuMan** [comment]
If this issue still exists, I would like to try to complete it
