### ISSUE TITLE
Replace user verified photo from url to an actual asset of the project 

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#152]
## Description

Verified icon for users is extracted from an URL instead of having the asset locally on the project. The goal is to download the image, put it into frontend assets and replace it in the code.

## How to do it

![image](https://github.com/AntonioMrtz/SpotifyElectron/assets/60626957/51e07c0e-d22b-48c7-8f1b-d6313b907795)

In line 251 of file `UserProfile.tsx`  replace the photo URL with the asset downloaded from the same URL.

## Testing

Start both frontend and backend and check if the verified photo looks the same as before

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove verified users icon from link to actual image](https://trello.com/c/3HpAV5cC/414-remove-verified-users-icon-from-link-to-actual-image)

**Comment by PavlisinPhoto** [comment]
Hello, I want to contribute on your project and I think this issue will be great start. Can you assign me this issue?

**Comment by AntonioMrtz** [comment]
Hi @PavlisinPhoto , welcome :). Let me know if you need anything

**Comment by AntonioMrtz** [comment]
Hi @PavlisinPhoto are you still working in this issue :) ? If you need help with something just let me know 🖐️

**Comment by PavlisinPhoto** [comment]
Hi @AntonioMrtz sorry for delay, I will do it :)
