### ISSUE TITLE
New Genre set and Rename Song Genres to english

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#154]
## Description

In both Frontend and Backend a Enum with the Genre value for songs is defined. This is useful for mapping the string value of the genres between frontend and backend. Some of the Genres dont have an english name and its desirable that theyre unified.

## Context

* The app was only in spanish so some of the genre still have the non translated name.
* The app will be migrated to be only in english. This includes all documentation, code...

## How to do it

Update Genre names both in frontend in backend ( they have to match in both sides ) and the comments associated.

#### Backend

Genres are defined in `genre_schema.py` file. Rename the non translated genres into english.

#### Frontend

Genres are defined in `genre.ts` file. Rename the genres to match the backend ones. Translate the comments about the associated color.

## Testing

* Run tests both for backend and frontend
* Launch the app and check if the following still works:

- Create song and selecting genre
- Search that song in explore section using the genre. Check if the song is under the genre included during its creation.

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rename Genres to english](https://trello.com/c/hbMz4kNT/416-rename-genres-to-english)

**Comment by Claudio-RL** [comment]
Puedo empezar con esta tarea?

**Comment by AntonioMrtz** [comment]
Main music Genres (replace old ones):

```
Pop
Rock
Jazz
Blues
Hip Hop / Rap
Electronic / EDM
Classical
Reggae
Country
Folk
R&B / Soul
Metal
Latin
Gospel
Punk
Funk
Disco
House
Techno
Indie
Alternative
Opera
Ambient
World Music
Trap
```

**Comment by AntonioMrtz** [comment]
Deprecated architecture for genres
