### ISSUE TITLE
Differentiate between BaseUser and User

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#159]
## Description

Differentiate between BaseUser and User by creating a Base class for all users and a User class that implements it, just like Artist is doing it at the moment.

## Context

User class serves as BaseUser class and Artist inherits from it. The issue appears when trying to implement new users like for example an admin. This type of user doesnt care about fields such as `playback_history` and so.

Currently User class is both a Base class and a Concrete one. This can lead to confusion because other inheritances in the app such as songs have a Base and Concrete class that are not the same.

The aim is to:

* Encapsulate common user attributes into a Base class `BaseUser`
* Create a concrete User class `User` that inherits from `BaseUser` and its being inherited by `Artists`.

Watch below for more info about the attributes:

```
@dataclass
class UserDAO:
    """Represents  user data in the persistence layer"""

    name: str - common
    photo: str - common
    register_date: str - common
    password: bytes - common
    playback_history: list[str] - user and its children classes
    playlists: list[str] - user and its children classes
    saved_playlists: list[str] - user and its children classes

@dataclass
class ArtistDAO(UserDAO):
    """Represents artist data in the persistence layer"""

    uploaded_songs: list[str] - artist and its children classes
```

## How to do it

* Create `BaseUser`
* Modify `User`
* Change type annotations from User to BaseUser in the common methods

## Testing

* Ensure old functionalities still works
* Test new funcionality

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Base User as Abstract](https://trello.com/c/WR3OGIX4/404-create-base-user-as-abstract)

**Comment by AlesSust** [comment]
Hi @AntonioMrtz. I saw your issue and I would like to contribute to project Would you assign this to me? :)
