### ISSUE TITLE
Unify Backend validations

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#164]
## Description

Unify validations methods for each entity in backend so theyre consistent.

## Context

Theres validation methods that are named `handle`. We also want to make all validations method consistent on both behaviour and syntax.

## How to do it

Rename validations using the same pattern and ensure the structure and behaviour is consistent.

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unify Backend validations](https://trello.com/c/FWDuTvro/431-unify-backend-validations)

**Comment by aarshgupta24** [comment]
Hi @AntonioMrtz , i will start on this one

**Comment by aarshgupta24** [comment]
Hi @AntonioMrtz , I think im done with task , so should i go for pull request?

**Comment by aarshgupta24** [comment]
just a small doubt , i will use the prefix refactor or is it something else?

**Comment by AntonioMrtz** [comment]
Yeah, refactor is good @aarshgupta24

**Comment by aarshgupta24** [comment]
@AntonioMrtz , is this issue completed then ?

**Comment by AntonioMrtz** [comment]
@aarshgupta24 It will be closed once the PR is merged.

**Comment by aarshgupta24** [comment]
so i should not  perform ruff linting and formatting ?
