### ISSUE TITLE
Warning logs for default selections & mappers

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#165]
## Description

Add `logger.warning` to events that can lead to future problems. [Providers](https://github.com/AntonioMrtz/SpotifyElectron/blob/master/Backend/app/spotify_electron/song/providers/song_service_provider.py) or mappers are a clear example. Log in warning level if theres no mapping available and the default is being loaded.

## Context

Dynamic load such as mappers and providers cant have an assigned value and will load a default value.

## How to do it

Check that every mapper/provider is logging a warning if the default value is being used. Also check PropertiesManager, it has some default selections for architecture.

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Warning logs for default selections & mappers](https://trello.com/c/XT7u6Drw/430-warning-logs-for-default-selections-mappers)

**Comment by aarshgupta24** [comment]
@AntonioMrtz , i had two doubts 
1 - 
playlist_collection_provider , here there is no need of logging right? 

2-
song_service_provider :


```
def _get_song_service(self) -> ModuleType:
    architecture_type = getattr(PropertiesManager, ARCHITECTURE_ENV_NAME)
    if architecture_type not in self.song_services:
        self.logger.warning(
            f"Missing mapping for architecture type:  {architecture_type}."
        )
    import_module = importlib.import_module(
        MODULE_PREFIX_NAME + self.song_services[architecture_type]
    )
    self.logger.info(f"Song service MODULE selected : {architecture_type}")
    return import_module
```


Does this seems correct im kind of confused as we are already setting default value in properties_manager,
and also if this is correct then i have to return default module  or not?

**Comment by AntonioMrtz** [comment]
> @AntonioMrtz , i had two doubts 1 - playlist_collection_provider , here there is no need of logging right?
> 
> 2- song_service_provider :
> 
> ```
> def _get_song_service(self) -> ModuleType:
>     architecture_type = getattr(PropertiesManager, ARCHITECTURE_ENV_NAME)
>     if architecture_type not in self.song_services:
>         self.logger.warning(
>             f"Missing mapping for architecture type:  {architecture_type}."
>         )
>     import_module = importlib.import_module(
>         MODULE_PREFIX_NAME + self.song_services[architecture_type]
>     )
>     self.logger.info(f"Song service MODULE selected : {architecture_type}")
>     return import_module
> ```
> 
> Does this seems correct im kind of confused as we are already setting default value in properties_manager, and also if this is correct then i have to return default module or not?

Hi @aarshgupta24 .

1. Theres no need really because there isnt any default selection of the argument is not provided.
2. As you say, default selection is made on properties_manager. The log should be in `properties_manager`, but in this case I think it already exists. No need to log everything extra on `_get_song_service`

**Comment by AntonioMrtz** [comment]
@aarshgupta24 , yeah, I will check it out as soon as possible
