### ISSUE TITLE
Calculated field/property for artists total streams

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#227]
## Description

Calculated field/property(MongoDB) for artists total streams, when artist is retrieved from database the field streams should have the calculated amount of streams of all of their songs.

## Context

Currently artist's streams are calculated by iterating over their songs in a separate query:

```
def get_song_names_search_by_name(song_name: str) -> list[str]:
        ....
        collection = song_collection_provider.get_song_collection()
        song_names_response = collection.find(
            {"name": {"$regex": song_name, "$options": "i"}}, {"_id": 0, "name": 1}
        )
        return [song["name"] for song in song_names_response] 
```

## How to do it

- Delete endpoint for getting artist's streams
- Add a calculated field in `ArtistDAO` and `ArtistDTO` for total streams of artist's songs.

## Testing

- Modify existing get total streams for artist test. It should work with the new artist calculated attribute

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Artist streams calculated property](https://trello.com/c/0nRC9z1U/258-artist-streams-calculated-property)

**Comment by ErikMisencik** [comment]
Hello it is possible to contribute to this issue ?

**Comment by AntonioMrtz** [comment]
HI @ErikMisencik , of course 😃. Let me know if you need anything. We also have docs [here](https://antoniomrtz.github.io/SpotifyElectron/) for common tasks/problems.

**Comment by ErikMisencik** [comment]
I have some questions. Do you have some platform like Discord etc. to send questions about Issue ? :D To avoid unnecessary messages here in the issue. @AntonioMrtz

**Comment by AntonioMrtz** [comment]
Hi @ErikMisencik, we can use Discord if that works for you, or we can use the associated Trello task. I’m fine with either option.
