### ISSUE TITLE
Only allow audio files for song uploading

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#239]
## Description

Only allow audio files for song uploading in file picker

## Context

Current file picker for uploading songs accepts all file formats, restrict

## How to do it

Modify form file input for only accepting audio files

```
<button
  type="button"
  onClick={handleSubmitSong}
  className={`btn btn-lg ${styles.btnSend} d-flex flex-row justify-content-center`}
  data-testid="sidebar-addsongplaylistaccordion-submit-song"
>
  Subir 
  {loadingUploadSong && <LoadingCircleSmall />}
</button>

```

## Testing

* Update tests if needed
* Test uploading invalid file type and most common audio file types (max 4 items). Files can be created empty so they don't inscrese repo size

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Only allow mp3 files for song uploading](https://trello.com/c/PdlPFRJf/517-only-allow-mp3-files-for-song-uploading)

**Comment by AntonioMrtz** [comment]
Hi @perig99 , all yours :smile: . Let me know if you have any questions.

**Comment by AntonioMrtz** [comment]
@perig99 Thank you for sharing your time with the project , I did a little update on the issue based on a research on our backend streaming. Instead of only allowing MP3 it is required to accept all audio files :)

**Comment by perig99** [comment]
Hi @AntonioMrtz ,
I can prevent to upload all audio files by changing `<input accept="audio/mp3">` attribute to `"audio/*"` like this:
```
<input
      className={`form-control-md ${styles.input}`}
      type="file"
      id="file"
      name="file"
      onChange={handleChangeFile}
      accept="audio/*"
      required
      data-testid="sidebar-file-input"
/>
```

This aproach will show "Audio files" (Zvukové súbory in my language) as default in file explorer picker. But there is a little problem. In file explorer there is still next option to show "All files" (Všetky súbory in my language) from picker. When user change it to "All files" he can choose any format. After my research on the internet, I found  that there is no option tu restrict this behaviour from html `<input>` element.

![image](https://github.com/user-attachments/assets/5d53d3a9-e01d-4968-bf4c-28a94ee9a94c)
![image](https://github.com/user-attachments/assets/3a78b9c2-bf58-4402-95fd-456f7d200954)


So I thinking how to solve this. If I can, my aproach is to modify function `handleChangeFile` to prevent that there will be accepted only audio file. (I can provide code snippet too if you want.) After choosing wrong file format (not audio) there is alert:

web:
![image](https://github.com/user-attachments/assets/5a97a29e-c16e-4279-8b0b-2a317102ef14)

app:
![image](https://github.com/user-attachments/assets/e45060a5-9a76-4fd2-be2e-43f794f75b7c)


Please let me know, if you are OK wuth this or I should choose different aproach. Thanks. :)

**Comment by AntonioMrtz** [comment]
Hi @perig99 it sounds really good. Yeah, handling unsupported files in `handleChangeFile` is the best idea. We will be reworking popover info messages so just emptying the file field if it's unsupported should be enough. 😃

**Comment by perig99** [comment]
Hi @AntonioMrtz,
I have created a [PR](https://github.com/AntonioMrtz/SpotifyElectron/pull/240).

**Comment by AntonioMrtz** [comment]
Yes, I got a notification about it. I will take a closer look at the PR tomorrow :). Thanks for your time
