### ISSUE TITLE
Improve Cold Start requests by adding timeout and blocking user input 

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#261]
## Description

Improve Cold Start requests by adding timeout and blocking user input like buttons when the request is being processed

## Context

In production, when the server is having a cold start, there're multiple requests that can block the app until a response is given. Cold start can be near 50s. We want to cancel the request if it's taking too long.

## How to do it

There're 3 requests that can be done for connecting for the first time with the server:

* Autologin | [StartMenu.tsx](https://github.com/AntonioMrtz/SpotifyElectron/blob/master/Electron/src/pages/StartMenu/StartMenu.tsx)
* Login | [StartMenu.tsx](https://github.com/AntonioMrtz/SpotifyElectron/blob/master/Electron/src/pages/StartMenu/StartMenu.tsx)
* Sign up | [RegisterMenu.tsx](https://github.com/AntonioMrtz/SpotifyElectron/blob/master/Electron/src/pages/StartMenu/RegisterMenu.tsx)

To solve this we expect to:

* Make the request timeout if it takes more than 5s (autologin, login, sign up)
* If timeout is reached show cold start message already implemented
* Block user input while processing the request (cant click login, sign up and login/sign switch buttons
* Show loading circle when one of the requests is being made

## Testing

Show the expected result ( popover message ) is thrown when start requests take more than a fixed amount of time

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Autologin + register + login request throw error cold start message if connection is taking too long (timeout)](https://trello.com/c/Au7EpcgY/534-autologin-register-login-request-throw-error-cold-start-message-if-connection-is-taking-too-long-timeout)

**Comment by gigigimay** [comment]
Hi, I would like to work on this. Can you assign this issue to me?

**Comment by AntonioMrtz** [comment]
Hi @gigigimay , all yours :). Tell my if you need anything, we also have the project docs [here](https://antoniomrtz.github.io/SpotifyElectron/)
