### ISSUE TITLE
Create Context for song and playlist currently being played

### ISSUE THREAD

**Issue by AntonioMrtz** [AntonioMrtz/SpotifyElectron#267]
## Description

Create Context for song and playlist currently being played

## Context

The current song being played is stored using a `useState` hook in top level component. We want to allow the current playing song to be accessed from any Component without prop drilling through several layers

## How to do it

* Create a context for the current song and playlist being played, include changesong setter method `changeSongName`
* Remove prop drilling for changing and getting current song, access it through the context instead

## Testing

---

__🖐️ Learn [how to CONTRIBUTE](https://antoniomrtz.github.io/SpotifyElectron/CONTRIBUTING), all help is welcomed :)__

__📚 Check out the [project documentation](https://antoniomrtz.github.io/SpotifyElectron/) for more info__

__⭐ Help this project grow by giving it a star if you like it!__

__😵 Trello links are used for traceability, do not ask to join the board before leaving a comment in the related issue__

**Comment by AntonioMrtz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PlayingContext for current song and playlist](https://trello.com/c/9imyqG3d/492-playingcontext-for-current-song-and-playlist)

**Comment by SaurabhGurde** [comment]
I wanan try this

**Comment by AntonioMrtz** [comment]
Hi @SaurabhGurde , yeah, all yours. But I have to recommend you to look at the contributing guides and naming conventions :)
